# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_auto_20180309_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('viewname', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
