# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-27 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_staticpagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy',
            name='Bartlett1916_Notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Bartlett1939_Notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Lee_Notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='Local_Notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
