# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('census', '0006_auto_20180423_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=500)),
                ('thumbnail_URL', models.URLField(blank=True, max_length=500, null=True)),
                ('NSC', models.IntegerField(default=0, null=True)),
                ('Shelfmark', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Height', models.FloatField(default=0, null=True)),
                ('Width', models.FloatField(default=0, null=True)),
                ('Marginalia', models.TextField(blank=True, default=None, null=True)),
                ('Condition', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Binding', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Binder', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('Bookplate', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('Bookplate_Location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Bartlett1939', models.IntegerField(default=0, null=True)),
                ('Bartlett1939_Notes', models.TextField(blank=True, default=None, null=True)),
                ('Bartlett1916', models.IntegerField(default=0, null=True)),
                ('Bartlett1916_Notes', models.TextField(blank=True, default=None, null=True)),
                ('Lee_Notes', models.TextField(blank=True, default=None, null=True)),
                ('Local_Notes', models.TextField(blank=True, default=None, null=True)),
                ('prov_info', models.TextField(blank=True, default=None, null=True)),
                ('bibliography', models.TextField(blank=True, default=None, null=True)),
                ('from_estc', models.BooleanField(default=False)),
                ('location_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Base copies',
            },
        ),
        migrations.AlterModelOptions(
            name='staticpagetext',
            options={'verbose_name_plural': 'Static Pages'},
        ),
        migrations.CreateModel(
            name='CanonicalCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
            ],
            options={
                'verbose_name_plural': 'Canonical copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.CreateModel(
            name='DraftCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='census.CanonicalCopy')),
            ],
            options={
                'verbose_name_plural': 'Draft copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.CreateModel(
            name='FalseCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
            ],
            options={
                'verbose_name_plural': 'False copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.CreateModel(
            name='HistoryCopy',
            fields=[
                ('basecopy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='census.BaseCopy')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='census.CanonicalCopy')),
            ],
            options={
                'verbose_name_plural': 'History copies',
            },
            bases=('census.basecopy',),
        ),
        migrations.AddField(
            model_name='basecopy',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_submitted_copies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basecopy',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='census.Issue'),
        ),
    ]
