# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0007_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
