# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_librarianemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LibrarianEmail',
        ),
    ]
