# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0009_contactform_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='verify',
        ),
        migrations.AddField(
            model_name='contactform',
            name='guardian',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
