# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0009_delete_librarianemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
