# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-31 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0012_contactform_guardian'),
        ('census', '0010_auto_20180807_1549'),
    ]

    operations = [
    ]
