# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-20 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0017_auto_20180918_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecopy',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='Owner',
        ),
    ]
