# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-10 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0018_auto_20180920_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecopy',
            name='NSC',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
