# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0019_auto_20181010_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecopy',
            name='NSC',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
