# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-10-26 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0020_auto_20181011_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookplate',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='bookplate_location',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='childcopy',
            name='copy_ptr',
        ),
        migrations.RemoveField(
            model_name='childcopy',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='copy',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='copyhistory',
            name='copy_ptr',
        ),
        migrations.RemoveField(
            model_name='copyhistory',
            name='stored_copy',
        ),
        migrations.RemoveField(
            model_name='provenance',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='copy',
        ),
        migrations.RemoveField(
            model_name='transfer_value',
            name='copy',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.DeleteModel(
            name='BookPlate',
        ),
        migrations.DeleteModel(
            name='BookPlate_Location',
        ),
        migrations.DeleteModel(
            name='ChildCopy',
        ),
        migrations.DeleteModel(
            name='Copy',
        ),
        migrations.DeleteModel(
            name='CopyHistory',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Provenance',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
        migrations.DeleteModel(
            name='Transfer_Value',
        ),
    ]
