# Generated by Django 5.2.12 on 2026-03-14 19:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0025_auto_20260313_1555"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
