# Generated by Django 5.2.12 on 2026-03-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0027_add_missing_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecopy",
            name="binding",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
