# Generated by Django 2.0.9 on 2026-03-16

from django.db import migrations


class Migration(migrations.Migration):
    """
    Create tables that exist in production and in Django ORM state (from 0025)
    but were never created via migrations. This allows fresh databases (dev/staging)
    to match production schema.
    """

    dependencies = [
        ("census", "0028_alter_basecopy_binding"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],  # State already correct from migration 0025
            database_operations=[
                # census_rejecteddraftcopy - multi-table inheritance from BaseCopy
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS census_rejecteddraftcopy (
                            basecopy_ptr_id integer NOT NULL PRIMARY KEY
                                REFERENCES census_basecopy(id) DEFERRABLE INITIALLY DEFERRED,
                            date_created timestamp with time zone NOT NULL,
                            parent_id integer NULL
                                REFERENCES census_canonicalcopy(basecopy_ptr_id) DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE INDEX IF NOT EXISTS census_rejecteddraftcopy_parent_id_idx
                            ON census_rejecteddraftcopy(parent_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS census_rejecteddraftcopy;",
                ),
                # census_copyform
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS census_copyform (
                            id integer NOT NULL PRIMARY KEY
                                GENERATED BY DEFAULT AS IDENTITY,
                            shelfmark varchar(500) NULL,
                            height double precision NULL,
                            width double precision NULL,
                            rasmussen_west integer NULL,
                            rasmussen_west_notes text NULL,
                            prov_info text NULL,
                            marginalia text NULL,
                            binding varchar(500) NULL,
                            binder varchar(500) NULL,
                            location_id integer NULL
                                REFERENCES census_location(id) DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE INDEX IF NOT EXISTS census_copyform_location_id_idx
                            ON census_copyform(location_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS census_copyform;",
                ),
                # census_provenancename
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS census_provenancename (
                            id integer NOT NULL PRIMARY KEY
                                GENERATED BY DEFAULT AS IDENTITY,
                            name varchar(255) NULL,
                            bio varchar(255) NULL,
                            viaf varchar(255) NULL,
                            start_century varchar(255) NULL,
                            end_century varchar(255) NULL,
                            gender varchar(255) NULL
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS census_provenancename;",
                ),
                # census_provenanceownership
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS census_provenanceownership (
                            id integer NOT NULL PRIMARY KEY
                                GENERATED BY DEFAULT AS IDENTITY,
                            copy_id integer NOT NULL
                                REFERENCES census_canonicalcopy(basecopy_ptr_id) DEFERRABLE INITIALLY DEFERRED,
                            owner_id integer NOT NULL
                                REFERENCES census_provenancename(id) DEFERRABLE INITIALLY DEFERRED
                        );
                        CREATE INDEX IF NOT EXISTS census_provenanceownership_copy_id_idx
                            ON census_provenanceownership(copy_id);
                        CREATE INDEX IF NOT EXISTS census_provenanceownership_owner_id_idx
                            ON census_provenanceownership(owner_id);
                    """,
                    reverse_sql="DROP TABLE IF EXISTS census_provenanceownership;",
                ),
            ],
        ),
    ]
