# Generated by Django 5.2.12 on 2026-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0029_create_missing_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalcopy",
            name="provenance_search_names",
            field=models.ManyToManyField(
                through="census.ProvenanceOwnership",
                through_fields=("copy", "owner"),
                to="census.provenancename",
            ),
        ),
        migrations.AlterField(
            model_name="provenancename",
            name="end_century",
            field=models.TextField(
                blank=True,
                choices=[
                    ("17", "Pre-1700"),
                    ("18", "18th-Cenutry"),
                    ("19", "19th-Century"),
                    ("20", "Post-1900"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="provenancename",
            name="gender",
            field=models.TextField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("U", "Unknown"),
                    ("X", "N/A"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="provenancename",
            name="start_century",
            field=models.TextField(
                blank=True,
                choices=[
                    ("17", "Pre-1700"),
                    ("18", "18th-Cenutry"),
                    ("19", "19th-Century"),
                    ("20", "Post-1900"),
                ],
                null=True,
            ),
        ),
    ]
