name: CI

on:
  pull_request:
  push:
    branches:
      master

permissions:
  contents: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}

env:
  DOCKER_BUILDKIT: "1"
  DOCKER_IMAGE: "registry.revsys.com/shakespeare"

jobs:

  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15.1
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports: ['5432:5432']
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Git - Get Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          python -m uv pip install --system --requirement requirements.txt
          python -m uv pip install --system prek

      - name: Test with pytest
        env:
          DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
          DJANGO_SECRET_KEY: 'for-testing-only'
        run: |
          python -m pytest

      - name: Lints with prek
        run: |
          python -m prek run --all-files

  build:
    needs: [test]
    name: Build and Publish Docker image
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Git - Get Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Git Tags
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip uv
          python -m uv pip install --system vinnie

      - name: Bump and Tag our version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          vinnie patch
          git push --tags

      - name: Docker - Login
        uses: docker/login-action@v4
        with:
          registry: registry.revsys.com
          username: shakespeare
          password: ${{ secrets.REVSYS_DOCKER_REGISTRY_PASSWORD }}

      - name: Build Docker image
        env:
          DJANGO_SECRET_KEY: 'for-testing-only'
        run: |
          TAG=`vinnie version`

          docker build --build-arg TAG=${TAG} \
            --cache-from=${DOCKER_IMAGE}:latest \
            --tag ${DOCKER_IMAGE} .

      - name: Docker - Tag
        run: |
          TAG=`vinnie version`

          docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE}:latest
          docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE}:${TAG}

      - name: Docker list images
        run: |
          docker images

      - name: Docker - Push
        run: |
          TAG=`vinnie version`
          docker push ${DOCKER_IMAGE}:latest
          docker push ${DOCKER_IMAGE}:${TAG}

          echo "Pushing registry.revsys.com/shakespeare:$TAG"
          echo "## Docker Image Pushed" >> $GITHUB_STEP_SUMMARY
          echo "Image: registry.revsys.com/shakespeare:$TAG" >> $GITHUB_STEP_SUMMARY
